### ISSUE TITLE
Filter based on branch/pr

### ISSUE THREAD

**Issue by villelahdenvuo** [cloudradar-monitoring/circleci-orbs#1]
Hey, thanks for the great orb, it's working nicely!

I would like to only be notified on specific branches, such as develop, master and release-*. Or disable notifications on PRs. It seems like CircleCI allows some basic filtering, but does not support wildcard matching nor PR information:

```yaml
notify_teams: &notify_teams
  - when:
      condition:
        or:
          - equal: [ master, << pipeline.git.branch >> ]
          - equal: [ develop, << pipeline.git.branch >> ]
          - equal: [ /release-.*/, << pipeline.git.branch >> ] # does not work
      steps:
        - ms-teams/report:
            only_on_fail: true
            webhook_url: $TEAMS_WEBHOOK_URL
```

Would it be possible to add a parameter to the orb to ignore PRs or branch patterns?
